version: '3'

services:
  nginx:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
#volumes:
#     - ./data/work:/opt/adguardhome/work
#     - ./data/conf:/opt/adguardhome/conf
    ports:
      - "8080:80/tcp"
      - "44343:443/tcp"
      - "44343:443/udp"
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "6868:68/udp"
      - "3000:3000/tcp"
      - "853:853/tcp"
      - "853:853/udp"
      - "784:784/udp"
      - "8853:8853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
